# cuda
cuda_index: 5

# path
data_dir: '/hadata/weim/zzh/emotionmoe/data'
dataset_dir: 'dataset'
preprocessed_dir: preprocessed
target_dir: save
bert_path: "/storage/nfs2/ModelHub/roberta-base"
pretrained_model_path: '/hadata/weim/zzh/emotionmoe/data/save/best_model/best_model_seed=555_top_k=2_f1=0.5838.pt'  # 新增：预训练模型路径


# training
batch_size: 4
epoch_size: 8
dropout: 0.1
max_length: 35
total_length: 512
loss_weight: 2.0
shuffle: True
bert_lr: 1e-5
learning_rate: 1e-4
patience: 100
max_grad_norm: 1.0
warmup_proportion: 0.1
gradient_accumulation_steps: 1
adam_epsilon: 1e-7
warmup_steps: 0
weight_decay: 0.00

# tokens（更新为RoBERTa的特有token）
pad: '<pad>'
unk: '<unk>'
cls: '<s>'
sep: '</s>'
min_freq: 2

# seed
seed: 555

# model parameters
emo_cat: 'yes'
audio_dim: 6373
video_dim: 4096
hid_size: 400

alpha: 5
hidden_dim: 400


# EmotionMoE parameters
num_experts_per_emotion: 4
num_shared_experts: 1    # 改为 1
top_k: 2
top_m: 3
neutral_weight: 0
gamma: 0.01
#initial_gamma: 0.5
lambda_sequence: 0.001      # 轻量序列级损失权重

# label dictionary
label_dict:
  neutral: 0
  anger: 1
  disgust: 2
  fear: 3
  joy: 4
  sadness: 5
  surprise: 6